### ISSUE TITLE
MVP приложения 

### ISSUE THREAD

**Issue by dyakovri** [profcomff/aggregator-app#1]
По прототипу в [Figma](https://www.figma.com/file/gfvuDN9x7I7sFCJQ7b1bIz/Agregator?node-id=14%3A21) разработать:
- [x] Инициализировать приложение Vue с поддержкой PWA
- [x] Компоненты шапки и нижнего меню 
- [x] Подключить роутер
- [x] Разработать View (`/timetable`) для страницы расписания (шапка+меню+iframe на расписание) 
- [x] Разработать View (`/apps`) для страницы приложений (шапка+меню+список приложений в сетке 3хN)

Допущения и комментарии:
* В верхнем меню не нужно делать кнопку аккаунта, для нее пока нет сервиса
* На страницы расписания iframe указывает на http://ras.phys.msu.ru
* В меню приложений те же приложения, что есть на странице https://student-app.ru/mgu/fizfuk + принтер https://app.profcomff.com/print-ui/ 
* Страницы приложений открываются в отдельной вкладке (при желании их можно открывать в iframe как расписание и добавить кнопку "назад" вместо иконки аккаунта)
* Выпадающее меню в верхнем правом углу имеет кнопки "Перезагрузить" (обновляет текущую страницу) и "О программе" (View `/about` с Lorem Ipsum..., или просто кнопка, которая ничего не делает)
* Иконки и идеи для дизайна брались с официального сайта Material Design (Material Design 3), так что следуя этим гайдлайнам все должно получиться хорошо 
* Точные цвета и иконки можешь попросить в личке

**Comment by phill-kiselev** [comment]
http://ff-test-39573.herokuapp.com/
Рома:
Можешь в iFrame пока поместить ras.phys.msu.ru, чтоб не пустовало, пусть это будет главная
Нижнее меню лучше сделать по высоте постоянное, в 56 пикселей. Гугл говорит, что это должны быть dp – density independant pixel, dp = (width in pixels * 160) / screen density, но пока и просто пиксели норм будут

**Comment by dyakovri** [comment]
Для иконок можно на уровне приложения подключить Google Material Icons Font (https://fonts.google.com/icons). Вряд ли мелкие иконки мы будем отрисовывать свои

**Comment by phill-kiselev** [comment]
Notes:
1. Fonts incorrect now (from figma 'Roboto')
2. iframe width is for desktop (and not zooming by fingers)
