### ISSUE TITLE
Иконка приложения синяя, хотя оттенок иконки фф темно-синий

### ISSUE THREAD

**Issue by dyakovri** [profcomff/aggregator-app#16]
Подменить иконку приложения в aggregator и заменить цвета в manifest.json

![Image](https://user-images.githubusercontent.com/51162917/188280985-9be29e7d-5afd-46cd-903e-acf11e5446c8.png)

**Comment by annndruha** [comment]
https://github.com/profcomff/aggregator-app/commit/901c26376b2bd0ca848dd13802d8f107257199bf
