### ISSUE TITLE
Попробовать создать якорь в ссылке на учебную часть

### ISSUE THREAD

**Issue by annndruha** [profcomff/aggregator-app#17]
Когда открываешь из приложения "Учебная часть", то открывается сайт учебки.

Сайт учебки кривой с телефона, и основная информация уползает вниз. (Кажется что её нет)

У хрома недавно появились якоря на любой текст на странице. Нужно проверить поддерживается ли этот якорь другими бразуерами.

Если поддерживается, то скролить учебку сразу  контенту.

![Image](https://user-images.githubusercontent.com/51162917/188299373-9685ebea-61cf-4080-9ea8-27625aad9c80.jpg)

**Comment by dyakovri** [comment]
Воспроизвести не вышло, но заменил ссылку на:
https://phys.msu.ru/rus/students/obshaja_infa.php#:~:text=%D0%98%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8F%20%D1%83%D1%87%D0%B5%D0%B1%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D0%B0

Скорее всего должно помочь
