### ISSUE TITLE
Front accessibility

### ISSUE THREAD

**Issue by mrerro** [profcomff/aggregator-app#22]
Доступность для людей с отклонениями. 

https://www.w3.org/WAI/fundamentals/accessibility-intro/

https://youtu.be/Q7kCUNC23vw?t=2414

**Comment by netsvetoch** [comment]
И не только для людей с отклонениями. На самом деле доступность — это про всех. Например, сломал ты руку, тебе было бы удобнее пользоваться интерфейсом с клавиатуры. Отдыхаешь ты на пляже — без достаточного контраста в приложении ты ничего не увидишь

**Comment by mrerro** [comment]
фикшено в новом фронте
